### ISSUE TITLE
Feature Request: Freeze gameplay while controlling camera

### ISSUE THREAD

**Issue by IceWolf762** [etra0/botw-freecam#24]
Unless I've overlooked something, would it be possible to pause/freeze the gameplay while the camera is being controlled? It could make for some really good screenshots of enemies attacking.

**Comment by etra0** [comment]
Duplicate of https://github.com/etra0/botw-freecam/issues/8. I've been messing with some options but so far it hasn't be a trivial thing to do. Physics engine tends to break quite easily.
