### ISSUE TITLE
"Function signature doesn't match"

### ISSUE THREAD

**Issue by Drflash55** [etra0/botw-freecam#25]
Getting this error when trying to use the freecam.
![image](https://user-images.githubusercontent.com/13694448/115815712-70b92a00-a3c5-11eb-98d7-fd8b460acf6c.png)

My CPU is a Ryzen 5 5600X, so that can't be the issue with the "MOVBE" instruction.
As for the version I'm using, I did use the latest version of CEMU and V1.22.2 on BOTW V1.5.0, DLC V3.0.

But my version of BOTW is European, so I dunno if that might have something to do with it.

**Comment by etra0** [comment]
Are you running any kind of trainer/cheat engine table/memory modification tool?
If so, try running the freecam without it.

**Comment by Drflash55** [comment]
Ah, yes. I was re-directed here from Postposterous' video, where he mentioned about using his own Cheat Table to stop time, which I was trying to use alongside it.

I'll use it without that to see if it fixes anything.
