### ISSUE TITLE
Timestop/pause function?

### ISSUE THREAD

**Issue by BoukObelisk** [etra0/botw-freecam#26]
Thank you etra0 for an amazing free camera! It's super amazing and works flawlessly. 

Do you think it would be possible to do a timestop function that can pause the action to make it easier to take cool shots of combat and so on? I completely understand if it's not possible. In any case, thanks a lot, I really appreciate your work.

**Comment by etra0** [comment]
Duplicate of https://github.com/etra0/botw-freecam/issues/8.
