### ISSUE TITLE
XInput blocker couldn't be found Cemu 1.26.0d

### ISSUE THREAD

**Issue by Myndmelt** [etra0/botw-freecam#33]
Hello!
Curious to know what may be the cause of the issue: Here is my botw.log contents
Not sure what Xinput blocker is.

13:16:58 [INFO] Breath of the Wild freecam by @etra0, v0.2.5.ca8ab08
13:16:58 [INFO] Waiting for the game to start
13:16:58 [INFO] Pointer found
13:16:58 [INFO] CameraOffsets { camera: 26b77a7910b, rotation_vec1: 26b6bb0fa84 }
13:16:58 [INFO] Camera function camera_pointer: 26b77a7910b
13:16:58 [ERROR] Something went wrong:
XInput blocker couldn't be found

Thanks!

**Comment by etra0** [comment]
XInput blocker basically takes over the joystick from the game. Probably the function was modified a bit in the newer version. I'll check it out this afternoon.

**Comment by WorriedArrow** [comment]
I'm having the same issue. Thanks for checking it out!

**Comment by etra0** [comment]
Fixed in 0.2.6. This version is now incompatible with old ones.

**Comment by WorriedArrow** [comment]
Thank you so much for fixing this!
