### ISSUE TITLE
xinput + jump table problem

### ISSUE THREAD

**Issue by Skysaure** [etra0/botw-freecam#38]
ive tried for so long i dont even know what to say but i keep getting this error 
![image](https://github.com/user-attachments/assets/4b72a1a5-c3eb-455b-8ffa-ad743f08035a)

**Comment by etra0** [comment]
You're not using the latest version of the tool, try with either

https://github.com/etra0/botw-freecam/releases/tag/v0.2.7-rc1

or

https://github.com/etra0/botw-freecam/releases/tag/v0.2.6

**Comment by Skysaure** [comment]
nope still the same issue 
![image](https://github.com/user-attachments/assets/e1b516a7-c115-435f-975f-4152bfcbdd30)

**Comment by Skysaure** [comment]
tried both versions

**Comment by etra0** [comment]
Are you opening the tool once the game is loaded? You have to at least get into the main menu iirc

**Comment by Skysaure** [comment]
this work thank you
