### ISSUE TITLE
Jittering when the duration is too long

### ISSUE THREAD

**Issue by etra0** [etra0/botw-freecam#4]
There's some noticeable jittering when the duration of the path is too long.

**Comment by mistermark** [comment]
Also happens when the path isn't very long. I seems to happen just randomly.

I've had it occur even when travelling a very small distance. But i've also not have it happen to me when I've been using the camera for a LONG time, like an hour.

**Comment by etra0** [comment]
I think it could be related to CPU usage. Since it's using a sleep, if your CPU is under stress it'll give way less priority and can cause that jitter. 
Would you mind telling me how many cores do you have @mistermark ? I'll do some testing too.

**Comment by etra0** [comment]
So the issue was a math singularity, not the scheduler (so it's not a CPU bound problem). This issue happens when you activate the freecam too near to link (that includes the first person mod). In the latest version (v0.2.5) this issue is fixed. 

Thanks a lot to [Wackiger](https://twitter.com/Wackiger) for helping me with the replication of the bug!
